#!/usr/bin/env bash
# script to install and setup nginx
FILE="/etc/nginx/sites-available/default"

apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /usr/share/nginx/html/index.html

# update config file to redirect
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://google.com/;
    }
}" > $FILE

service nginx start
