#!/usr/bin/env bash
# script to install and setup nginx
FILE="/etc/nginx/sites-available/default"

apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html


printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://google.com/;
    }

    error_page 404 /404.html;
    location /404 {
	root /etc/nginx/html;
	internal;
    }
}" > $FILE

service nginx start
