#!/usr/bin/env bash
# this script displays "Best School" 10 times
# except for the 9th iteration

i=0

while [ $i -lt 10 ]; do
	if [ $i -ne 8 ]; then
		echo "Best School"
	else
		echo "Hi"
	fi
	((i++))
done
