#!/usr/bin/env bash
# this script displays "Best School" 10 times
# except for the 9th iteration

i=0

while [ $i -lt 10 ]; do
	echo "Best School"

	if [ $i -eq 8 ]; then
		echo "Hi"
	fi
	((i++))
done
