#!/usr/bin/env bash
# this script prints "bad luck" in 4th iteration
# prints "good luck" in the 8th iteration
# and "Best School" for the rest of the loop

i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
