#!/usr/bin/env bash
# this script follows the same as the last one

i=1

while [ $i -le 20 ]; do
	case $i in
		5)
			echo "bad luck from China"
			echo "$i"
			;;
		10)
			echo "bad luck from Japan"
			echo "$i"
			;;
		18)
			echo "bad luck from Italy"
			echo "$i"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
