#!/usr/bin/env bash
# this script is easy

hour=0
minute=1

while [ $hour -lt 13 ]; do
	echo "Hour: $hour"

	minute=1
	while [ $minute -le 59 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
