#!/usr/bin/env bash
# Displays the contents of the current directory in list format
# Only displays the part of the name after the first dash

list=$(ls)

for element in $list; do
	echo "$element" | cut -d '-' -f2
done
